name: CI/CD Pipeline with Python and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Install Dependencies and Run Lint and Tests in Docker Container
      run: |
        docker run my-app /bin/sh -c "\
        python -m pip install --upgrade pip && \
        pip install flake8 pytest && \
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi && \
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && \
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics && \
        pytest"

    - name: Push to DockerHub
      if: success()
      run: docker push my-app
